version: '3.1'
services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5644:5432

  daemon:
   image: mt940-daemon 
   restart: always
   ports:
    - 8081:8080

  ui:
   image: mt940-ui
   restart: always
   ports:
    - 8080:8080

